### ISSUE TITLE
Сайт: /login

### ISSUE THREAD

**Issue by pzakorko** [m20-sch57/strategy-trial#11]
Если пользователь уже зашел, страница /login пересылает пользователя на /home 
Если нет:
1.Шапка:  [общая шапка](https://github.com/m20-sch57/strategy-trial/issues/9)
2.Тело: 
-Username: поле ввода
-Password: поле ввода
-Remember me: галка
-Sign up: кнопка

Если пользователь правильно ввел логин и пароль, его переносит на /home (поскольку он теперь в системе). 
Если же введено не верно, пользователю предлагают еще раз ввести логин и пароль

**Comment by cookiedoth** [comment]
Справедливо.

**Comment by alexdany657** [comment]
А галка Remember me нужна? Большинство броузеров (firefox) делают это сами.
