### ISSUE TITLE
Main/NonMain

### ISSUE THREAD

**Issue by cookiedoth** [m20-sch57/strategy-trial#119]
**Нужно реализовать интерфейс выбора основного решения задачи.**

Элементы столбца *Type* в таблице посылок должны быть кликабельными, при нажатии на *Main* посылку она становится *NonMain*. При нажатии на *NonMain* посылку она становится *Main*, а предыдущая посылка становится *NonMain*.

* В useCasesAPI есть функция *changeMainSubmission(userId, subId)*. Нужно вызывать её в обоих случаях. **Первый случай не учитывается в этой функции, надо исправить.**

**Comment by alexdany657** [comment]
Я сделаю

**Comment by cookiedoth** [comment]
Лол

**Comment by cookiedoth** [comment]
Ссори, я уже сделал (не прочитал)
