### ISSUE TITLE
Сайт: /sign_up (?)

### ISSUE THREAD

**Issue by pzakorko** [m20-sch57/strategy-trial#12]
Шапка: [общая шапка](https://github.com/m20-sch57/strategy-trial/issues/9)
Тело:

-Поля ввода
First name (необязательно)
Surname (необязательно)
Create Username
Create Password
Again Password
Your email (?может ли он пригодиться?)
 
-Кнопка
Create account
______________________________________________________________________________________________
Далее нужно проверить:
-все ли поля заполнены
-не занят ли Username другим пользователем
-одинаковы ли поля "Create Password" и "Again Password"

Если хотя бы один пункт неверен:
-пользователю предлагается еще раз ввести данные
Иначе:
-переходит на страницу /home
______________________________________________________________________________________________
Куда переходят данные, введенные пользователем:
(????? В базу данных [здесь должна быть ссылка на базу данных]???????)

**Comment by cookiedoth** [comment]
Го без First Name и Surname

**Comment by pzakorko** [comment]
А если admin - это учитель, которому очень нужно знать, кто как написал стратегию?

**Comment by pzakorko** [comment]
Исправлено

**Comment by alexdany657** [comment]
А почему в Sign up форме нет поля повторите пароль?
