### ISSUE TITLE
Когда два турнира запускаются одновременно, происходит троллинг

### ISSUE THREAD

**Issue by cookiedoth** [m20-sch57/strategy-trial#125]
Надо сделать так, чтобы троллинг не происходил или чтобы нельзя было запустить одновременно два турнира.

**Comment by alexdany657** [comment]
Поясни, пожалуйста. Я пробовал и вроде все ОК

**Comment by alexdany657** [comment]
Правильно ли я понимаю, что раньше при запуске двух турниров мы добавляли в БД только один?

**Comment by cookiedoth** [comment]
Кажется, да. Там что-то странное происходило.

Мне кажется, стоит либо сделать флаг isTesterBusy, либо организовать очередь тестирования.

Возможно, я во время сборов смогу что-нибудь сделать по проекту (во всяком случае, я на это надеюсь).
