### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by alexdany657** [m20-sch57/strategy-trial#140]

**Comment by cookiedoth** [comment]
Написал

**Comment by cookiedoth** [comment]
Ну может кто-нибудь почитает?

**Comment by cookiedoth** [comment]
Вдруг там ерунда написана

**Comment by alexdany657** [comment]
Я читал, использую при написании игры, пока вроде все понятно. Правильно или нет пойму каак допишу и попробую добавить задачу.

**Comment by alexdany657** [comment]
Мне кажется, в разделе Docs, при описании логов, в импорты имеет смысл добавить `import os`, потому что я не заметил и скопировал твой код из примера чуть ниже.

**Comment by alexdany657** [comment]
особенно актуально тем, кто не знаком с модулем os

**Comment by alexdany657** [comment]
Мне кажется
Может быть я невнимательный

**Comment by cookiedoth** [comment]
Справедливо ;)

**Comment by cookiedoth** [comment]
Сейчас добавлю

**Comment by cookiedoth** [comment]
done

**Comment by alexdany657** [comment]
Спасибо
