### ISSUE TITLE
Создание задачи: downloads, кодировка

### ISSUE THREAD

**Issue by alexdany657** [m20-sch57/strategy-trial#183]
Надо обсудить, м. б. надо выкладывать архив на скачивание, чтобы не заморачиваться с кодировкой.

Кодировка: мы пока понимаем только UTF-8, или надо это фиксить, или надо твсе переводить в UTF-8

**Comment by cookiedoth** [comment]
Надо переводить...

**Comment by cookiedoth** [comment]
working...
