### ISSUE TITLE
Bug: submission can't be html!

### ISSUE THREAD

**Issue by pzakorko** [m20-sch57/strategy-trial#186]
Если отправить html в тестирующую систему, то на странице Submissions будет отображаться не текст кода, а его значение (т.е., например, появится картинка или табличка...). Короче, та же ошибка, что и в Discussions

**Comment by cookiedoth** [comment]
Имхо здесь лучше попытаться отображать как текст вне зависимости от контента. Попробую погуглить как это делать

**Comment by pzakorko** [comment]
Если заменять '<' на '&lt;', то html выглядет нормально. Я пока так сделала

**Comment by pzakorko** [comment]
github не очень хорошо отобразил '<'=' & l t ; '
