### ISSUE TITLE
Demo.Сайт: главная страница

### ISSUE THREAD

**Issue by cookiedoth** [m20-sch57/strategy-trial#24]
* Отображается список всех стратегий
* Каждая стратегия – ссылка, при нажатии на неё открывается исходный код
* Рядом с каждой стратегией галка
* Есть кнопка *Отправить стратегию* (перекидывает на соответствующую страницу)
* Есть кнопка *Тестировать стратегии*. Если выбрано ровно две стратегии, перекидывает на страницу с результатом.

**Comment by pzakorko** [comment]
А если более двух галок?

**Comment by cookiedoth** [comment]
В этом случае можно написать, что только две стратегии могут быть протестированы
