### ISSUE TITLE
Demo.Сайт: страница с кодом стратегии

### ISSUE THREAD

**Issue by cookiedoth** [m20-sch57/strategy-trial#25]
На странице исходный код стратегии в текстовом формате

**Comment by pzakorko** [comment]
Чьим кодом? С какой страницы можно попасть на эту страницу? Где хранятся все коды?

**Comment by cookiedoth** [comment]
Исходный код стратегии. На главной странице ссылки типа:
Стратегия 1
Стратегия 2
...

При нажатии на ссылку открывается код.

Его можно будет получить функцией getStrategyCode(id) (смотри issue 21)
