### ISSUE TITLE
Сайт: /home

### ISSUE THREAD

**Issue by pzakorko** [m20-sch57/strategy-trial#5]
Так выглядит страница /home в зависимомти от того, зашел ли пользователь:

если не зашел:
-Шапка: картинка, ссылки на страницы /home, /sign_up, /login
-В теле сайта: что-то типа "Welcome to Strategy Trial. Please login or sign up" (login и sign up - ссылки на соответствующие страницы)

если зашел:
-Шапка: картинка, ссылки на страницы /home, /problemset, /submissions, /settings, /logout
-В теле сайта: "Please select problem", ссылка в слове "problem" на /problemset, и обновленные задачи

**Comment by cookiedoth** [comment]
*swap зашёл и не зашёл

**Comment by cookiedoth** [comment]
> -В теле сайта: "Please select problem" и ссылки на задачу (A B C D E... или вместо букв названия игр)

Пусть лучше ссылки на задачи будут в /problemset. А в /home можно сделать анонсы новых задач или просто полезная информация (как это сделано на CF).

**Comment by pzakorko** [comment]
Справедливо
