### ISSUE TITLE
Сайт: /problemset

### ISSUE THREAD

**Issue by pzakorko** [m20-sch57/strategy-trial#50]
Представляет собой таблицу:
problem_id | problem_name | time_start | time_end | status (OK, WA...) | enter

enter - переход на страницу [/problemset/problem_id](https://github.com/m20-sch57/strategy-trial/issues/49)

**Comment by cookiedoth** [comment]
Между time_end и OK, WA должен быть статус RUNNING / UPSOLVING

**Comment by cookiedoth** [comment]
Мб сначала сделать problem_id | problem_name | enter и не показывать задачи, которые только ожидаются?
