### ISSUE TITLE
Найденные баги

### ISSUE THREAD

**Issue by pzakorko** [m20-sch57/strategy-trial#51]
1. Плохо работают cookies, нужно поставить много if
2. Если при входе в систему написать неверного пользователя, то сайт ругается. Нужен if
3. При регистрации в системе не появляется строка, сообщающая пользователю, что он не ввел данные
4. Не отображается картинка в шапке
5. ... (какие будут предложения?)

**Comment by cookiedoth** [comment]
1. Модуль для логина, не делать это во views.
2. Добавить if?
4. Нужно использовать urlfor

**Comment by alexdany657** [comment]
Остался только 3. И это проблема всех flash.

**Comment by pzakorko** [comment]
FLASH!!!
