### ISSUE TITLE
Write tic-tac-toe test strategies

### ISSUE THREAD

**Issue by elexunix** [m20-sch57/strategy-trial#7]
Наверное, можно написать тестовые стратегии для игры в крестики-нолики.

Одна будет ходить в первую свободную клетку, вторая - в рандомную свободную клетку.
Формат ввода/вывода в соответствии с [постом Семёна](https://github.com/orgs/m20-sch57/teams/strategytrial/discussions/2).

Я могу это сделать и положить в какую-нибудь ветку для тестирования проекта. Куда?

**Comment by cookiedoth** [comment]
Мы решили, что использовать файлы не очень.

Думаю, лучше сначала понять что такое стратегия (спойлер: функция).

**Comment by elexunix** [comment]
class GameState:
    a = ['...', '...', '...'];

class Turn:
    def __init__(self, r, c):
        self.r, self.c = r, c;

def Strategy(a: GameState, b: int) -> Turn:
    for i in range(3):
        for j in range(3):
            if (a[i][j] == '.'):
                return Turn(i, j);

def Strategy(a: GameState, b: int) -> Turn:
    while True:
        i, j = random.randint(0, 2), random.randint(0, 2);
        if (a[i][j] == '.'):
            return Turn(i, j);
