### ISSUE TITLE
Хеширование пароля

### ISSUE THREAD

**Issue by cookiedoth** [m20-sch57/strategy-trial#71]
Нужно использовать какой-нибудь алгоритм хеширования паролей.

**Comment by alexdany657** [comment]
Я делаю

**Comment by alexdany657** [comment]
А разве была не проблема изменения юзером своих кук?

**Comment by cookiedoth** [comment]
мб я пока не знаю какую проблему рассматривает автор

**Comment by alexdany657** [comment]
Я захешировал куки, а пароли лежат только в БД. (а она на сервере)

**Comment by cookiedoth** [comment]
Звучит очень справедливо
